#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_big5_extension_code_table.py

Build a stable physical DFS codepoint table for a Big5 append-only extension,
based on the reports generated by:
  * audit_big5_extension_feasibility.py
  * audit_dfs_physical_pages.py

This script does not patch dfs.asm or generate font binaries.  It assigns
physical DFS-safe codepoints to Big5 characters that were classified as
`extension-needed`, and writes machine-readable maps that later tools can use
to build extension font pages and patch the DFS engine.

Design goals:
  * Keep original CHS/base DFS codepoints stable.
  * Put Big5-only / one-S-to-many-T chars into newly enabled extension pages.
  * Keep CJK assignments stable even if optional non-CJK Big5 symbols are added.
  * Avoid stealing already-defined symbols such as $0105 = ˉ.

Typical usage:
  python3 src/tools/build_big5_extension_code_table.py --repo . --target cjk

Optional full visible Big5 map, using a small number of safe tail-page holes
when $14-$17,$20-$27,$2F-$3F are not quite enough:
  python3 src/tools/build_big5_extension_code_table.py --repo . --target all-visible
"""
from __future__ import annotations

import argparse
import csv
import math
import re
import unicodedata
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

VERSION = "big5-extension-code-table-2026-06-18-v4"
HEX_RE = re.compile(r"\$([0-9A-Fa-f]{1,4})")


def parse_code(s: str) -> int:
    s = str(s).strip()
    if not s:
        raise ValueError("empty code")
    if s.startswith("$"):
        return int(s[1:], 16)
    if s.lower().startswith("0x"):
        return int(s, 16)
    return int(s, 0)


def fmt_code(n: int) -> str:
    return f"${n:04X}"


def fmt_page(n: int) -> str:
    return f"${n:02X}"


def repo_path(repo: Path, p: str | Path) -> Path:
    q = Path(p)
    return q if q.is_absolute() else repo / q


def read_tsv(path: Path) -> List[dict]:
    if not path.exists():
        raise FileNotFoundError(path)
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f, delimiter="\t"))


def write_tsv(path: Path, fieldnames: Sequence[str], rows: Iterable[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t", lineterminator="\n")
        w.writeheader()
        for row in rows:
            w.writerow({k: row.get(k, "") for k in fieldnames})


def parse_charmap(path: Path) -> Tuple[Dict[str, int], Dict[int, List[str]]]:
    char_to_code: Dict[str, int] = {}
    code_to_chars: Dict[int, List[str]] = defaultdict(list)
    if not path.exists():
        return char_to_code, code_to_chars
    ascii_ws = " \t\r\n"
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        # Do not use str.strip(); it removes U+3000 IDEOGRAPHIC SPACE,
        # which is a real glyph key in this project.
        line = raw.lstrip(" \t\r")
        if not line or line.startswith(";") or "=" not in line:
            continue
        left, right = line.split("=", 1)
        ch = left.strip(ascii_ws)
        m = HEX_RE.search(right.strip(ascii_ws))
        if not ch or not m:
            continue
        code = int(m.group(1), 16)
        char_to_code[ch] = code
        code_to_chars[code].append(ch)
    return char_to_code, code_to_chars


def parse_pages(path: Path) -> List[int]:
    rows = read_tsv(path)
    pages: List[int] = []
    for r in rows:
        p_s = r.get("page", "").strip()
        if not p_s:
            continue
        p = parse_code(p_s)
        if p == 0:
            # Page $00 stays disabled because of control/NUL concerns.
            continue
        if p not in pages:
            pages.append(p)
    if not pages:
        raise SystemExit(f"No extension pages found in {path}")
    return pages


def parse_low_template(path: Path) -> List[int]:
    if path.exists():
        rows = read_tsv(path)
        lows: List[int] = []
        for r in rows:
            s = r.get("low_byte", "").strip()
            if not s:
                continue
            v = parse_code(s)
            if 0 <= v <= 0xFF and v not in lows:
                lows.append(v)
        if lows:
            return lows
    # Conservative fallback matching the observed 226-slot legacy CJK pages.
    # Avoid known text-control-ish holes used by the original table.
    banned = set([0x00, 0x14, 0x15, 0x16, 0x22, 0x3F]) | set(range(0x4B, 0x60)) | set(range(0xFD, 0x100))
    return [x for x in range(0x01, 0xFD) if x not in banned]


def parse_tail_spare_pages(s: str) -> List[int]:
    out: List[int] = []
    for part in s.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            start = parse_code(a)
            end = parse_code(b)
            for p in range(start, end + 1):
                if p not in out:
                    out.append(p)
        else:
            p = parse_code(part)
            if p not in out:
                out.append(p)
    return out


@dataclass(frozen=True)
class Slot:
    code: int
    page: int
    low: int
    source: str
    note: str


def build_extension_slots(pages: Sequence[int], lows: Sequence[int], used_codes: Set[int]) -> List[Slot]:
    slots: List[Slot] = []
    for p in pages:
        for lo in lows:
            code = (p << 8) | lo
            if code in used_codes:
                continue
            slots.append(Slot(code=code, page=p, low=lo, source="extension-page", note="new/expanded DFS page"))
    return slots


def build_tail_spare_slots(
    pages: Sequence[int],
    lows: Sequence[int],
    used_codes: Set[int],
    base_code_to_chars: Dict[int, List[str]],
    current_code_to_chars: Dict[int, List[str]],
) -> List[Slot]:
    slots: List[Slot] = []
    for p in pages:
        for lo in lows:
            code = (p << 8) | lo
            if code in used_codes:
                continue
            if code in base_code_to_chars or code in current_code_to_chars:
                continue
            slots.append(Slot(code=code, page=p, low=lo, source="legacy-tail-spare-hole", note="unused safe low on existing legacy page"))
    return slots


def is_extension_needed(row: dict) -> bool:
    return row.get("extension_needed", "").strip().lower() == "yes" or row.get("class_name", "") == "extension-needed"


def row_sort_key(row: dict) -> Tuple[str, str, str]:
    # classification.tsv is already sorted by primary Big5 byte order, but this
    # keeps output stable even if the input was manually edited.
    return (row.get("big5", ""), row.get("unicode", ""), row.get("ch", ""))



def apply_strict_compat_policy(rows: List[dict], policy: str) -> Tuple[List[dict], List[dict]]:
    """Avoid assigning multiple distinct visible Big5 chars to one DFS glyph.

    The v1/v2 audit treated every t2s-compatible row as reusable. That is
    display-unsafe for one-simplified-to-many-traditional cases such as
    出/齣: a DFS codepoint has one glyph, so one of those chars must go to
    extension. Under strict mode:

      * If the base DFS code already has an exact Big5 char, all t2s variants
        using that code become extension-needed.
      * If several t2s variants share a base code and there is no exact Big5
        char, keep the first by Big5 order as the canonical glyph patch and
        move the rest to extension.

    This keeps CHS/base bytes stable while making the full Big5 map visually
    correct.
    """
    rows2 = [dict(r) for r in rows]
    if policy == "legacy":
        return rows2, []

    by_code: Dict[str, List[dict]] = defaultdict(list)
    for r in rows2:
        code = (r.get("dfs_code") or "").strip().upper()
        if code:
            by_code[code].append(r)

    adjustments: List[dict] = []
    for code, rs in sorted(by_code.items()):
        exacts = [r for r in rs if r.get("class_name") == "base-exact"]
        patches = [r for r in rs if (r.get("class_name") or "").startswith("base-t2s")]
        if not patches:
            continue

        exact_chars = [r.get("ch", "") for r in exacts if r.get("ch")]
        if exact_chars:
            for r in patches:
                old_class = r.get("class_name", "")
                old_ext = r.get("extension_needed", "")
                r["class_name"] = "extension-needed-strict-exact-conflict"
                r["extension_needed"] = "yes"
                r["note"] = (r.get("note", "") + f"; strict policy: {code} has exact Big5 char(s) {''.join(exact_chars)}, so {r.get('ch','')} needs extension").strip("; ")
                adjustments.append({
                    "dfs_code": code,
                    "char": r.get("ch", ""),
                    "big5": r.get("big5", ""),
                    "old_class": old_class,
                    "new_class": r.get("class_name", ""),
                    "old_extension_needed": old_ext,
                    "new_extension_needed": r.get("extension_needed", ""),
                    "reason": f"exact Big5 char(s) already use this glyph: {''.join(exact_chars)}",
                })
            continue

        if len(patches) > 1:
            patches_sorted = sorted(patches, key=row_sort_key)
            keep = patches_sorted[0]
            keep["note"] = (keep.get("note", "") + f"; strict policy: canonical glyph patch for shared code {code}").strip("; ")
            for r in patches_sorted[1:]:
                old_class = r.get("class_name", "")
                old_ext = r.get("extension_needed", "")
                r["class_name"] = "extension-needed-strict-shared-t2s"
                r["extension_needed"] = "yes"
                r["note"] = (r.get("note", "") + f"; strict policy: shares {code} with canonical {keep.get('ch','')}, so {r.get('ch','')} needs extension").strip("; ")
                adjustments.append({
                    "dfs_code": code,
                    "char": r.get("ch", ""),
                    "big5": r.get("big5", ""),
                    "old_class": old_class,
                    "new_class": r.get("class_name", ""),
                    "old_extension_needed": old_ext,
                    "new_extension_needed": r.get("extension_needed", ""),
                    "reason": f"shared t2s glyph code; canonical kept as {keep.get('ch','')}",
                })

    return rows2, adjustments

def make_assignment_rows(
    cjk_rows: Sequence[dict],
    extra_rows: Sequence[dict],
    slots: Sequence[Slot],
    target: str,
) -> Tuple[List[dict], List[dict]]:
    ordered: List[Tuple[dict, str]] = []
    for r in cjk_rows:
        ordered.append((r, "cjk-extension"))
    if target in {"all-visible", "cjk-plus-extra"}:
        for r in extra_rows:
            cls = "non-cjk-visible-extension" if target == "all-visible" else "manual-extra-extension"
            ordered.append((r, cls))

    if len(ordered) > len(slots):
        missing = len(ordered) - len(slots)
        raise SystemExit(
            f"Not enough physical DFS slots: need {len(ordered)}, have {len(slots)}, shortfall {missing}. "
            "Try --use-tail-spares yes, add more tail spare pages, or extend the DFS page range beyond $3F."
        )

    extension_rows: List[dict] = []
    charmap_rows: List[dict] = []
    for idx, ((r, cls), slot) in enumerate(zip(ordered, slots)):
        ch = r.get("ch", "")
        ext_row = {
            "ext_index": idx,
            "char": ch,
            "unicode": r.get("unicode", ""),
            "big5": r.get("big5", ""),
            "category": r.get("category", ""),
            "t2s": r.get("t2s", ""),
            "dfs_code": fmt_code(slot.code),
            "page": fmt_page(slot.page),
            "low": fmt_page(slot.low),
            "slot_source": slot.source,
            "compat_class": cls,
            "note": slot.note,
        }
        extension_rows.append(ext_row)
        charmap_rows.append({"char": ch, "dfs_code": fmt_code(slot.code), "comment": f"Big5 {r.get('big5','')} {cls}"})
    return extension_rows, charmap_rows


def make_compat_rows(class_rows: Sequence[dict]) -> List[dict]:
    out: List[dict] = []
    for r in sorted(class_rows, key=row_sort_key):
        if r.get("extension_needed", "") == "yes":
            continue
        cls = r.get("class_name", "")
        if cls not in {"base-exact", "base-t2s-glyph-patch", "base-t2s-ime-glyph-patch", "base-t2s-compatible"}:
            continue
        out.append({
            "char": r.get("ch", ""),
            "unicode": r.get("unicode", ""),
            "big5": r.get("big5", ""),
            "category": r.get("category", ""),
            "dfs_code": r.get("dfs_code", ""),
            "compat_class": cls,
            "t2s": r.get("t2s", ""),
            "base_char_at_code": r.get("base_char_at_code", ""),
            "ime_reserved": r.get("ime_reserved", ""),
            "note": r.get("note", ""),
        })
    return out


def make_full_rows(compat_rows: Sequence[dict], ext_rows: Sequence[dict]) -> List[dict]:
    rows: List[dict] = []
    for r in compat_rows:
        rows.append({
            "char": r.get("char", ""),
            "unicode": r.get("unicode", ""),
            "big5": r.get("big5", ""),
            "category": r.get("category", ""),
            "dfs_code": r.get("dfs_code", ""),
            "compat_class": r.get("compat_class", ""),
            "slot_source": "base-compatible",
            "t2s": r.get("t2s", ""),
            "note": r.get("note", ""),
        })
    for r in ext_rows:
        rows.append({
            "char": r.get("char", ""),
            "unicode": r.get("unicode", ""),
            "big5": r.get("big5", ""),
            "category": r.get("category", ""),
            "dfs_code": r.get("dfs_code", ""),
            "compat_class": r.get("compat_class", ""),
            "slot_source": r.get("slot_source", ""),
            "t2s": r.get("t2s", ""),
            "note": r.get("note", ""),
        })
    rows.sort(key=lambda x: (x.get("big5", ""), x.get("unicode", ""), x.get("char", "")))
    return rows


def write_charmap_txt(path: Path, rows: Sequence[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "; Auto-generated Big5 DFS extension charmap fragment.",
        f"; Generated by build_big5_extension_code_table.py {VERSION}.",
        "; Do not include this wholesale in src/charmap.txt unless the importer is meant to accept full Big5.",
        "",
    ]
    for r in rows:
        ch = r.get("char", "")
        code = r.get("dfs_code", "")
        comment = r.get("comment", "")
        if ch and code:
            lines.append(f"{ch}={code} ; {comment}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_summary(
    path: Path,
    args: argparse.Namespace,
    pages: Sequence[int],
    lows: Sequence[int],
    tail_pages: Sequence[int],
    ext_rows: Sequence[dict],
    compat_rows: Sequence[dict],
    cjk_needed: int,
    extra_needed: int,
    extension_slots_count: int,
    tail_slots_count: int,
) -> None:
    by_source = Counter(r.get("slot_source", "") for r in ext_rows)
    by_cat = Counter(r.get("category", "") for r in ext_rows)
    by_class = Counter(r.get("compat_class", "") for r in ext_rows)
    lines: List[str] = []
    lines.append(f"build_big5_extension_code_table {VERSION}")
    lines.append(f"target={args.target}")
    lines.append(f"classification={args.classification}")
    lines.append(f"dfs_pages={args.dfs_pages}")
    lines.append(f"safe_lows={args.safe_lows}")
    lines.append(f"base_charmap={args.base_charmap}")
    lines.append(f"current_charmap={args.current_charmap}")
    lines.append(f"reserve_current_codes={args.reserve_current_codes}")
    lines.append(f"compat_policy={getattr(args, 'compat_policy', 'legacy')}")
    lines.append("")
    lines.append("inputs:")
    lines.append(f"  extension pages: {len(pages)} ({', '.join(fmt_page(p) for p in pages)})")
    lines.append(f"  lows per extension page: {len(lows)}")
    lines.append(f"  extension page capacity: {extension_slots_count}")
    lines.append(f"  tail spare pages: {len(tail_pages)} ({', '.join(fmt_page(p) for p in tail_pages) if tail_pages else '(none)'})")
    lines.append(f"  tail spare capacity used/available: {by_source.get('legacy-tail-spare-hole', 0)} / {tail_slots_count}")
    lines.append("")
    lines.append("needed:")
    lines.append(f"  CJK extension-needed rows: {cjk_needed}")
    lines.append(f"  non-CJK/manual extension-needed rows selected: {extra_needed if args.target in {'all-visible', 'cjk-plus-extra'} else 0}")
    lines.append(f"  total assigned extension rows: {len(ext_rows)}")
    lines.append(f"  compatible/base rows: {len(compat_rows)}")
    lines.append("")
    lines.append("assigned by slot source:")
    for k, v in sorted(by_source.items()):
        lines.append(f"  {k}: {v}")
    lines.append("")
    lines.append("assigned by compat class:")
    for k, v in sorted(by_class.items()):
        lines.append(f"  {k}: {v}")
    lines.append("")
    lines.append("assigned by category:")
    for k, v in sorted(by_cat.items()):
        lines.append(f"  {k}: {v}")
    lines.append("")
    lines.append("outputs:")
    lines.append("  big5_extension_physical_map.tsv")
    lines.append("  big5_compat_base_map.tsv")
    lines.append("  big5_full_physical_map.tsv")
    lines.append("  charmap_big5_extension.txt")
    lines.append("  extension_pages_used.tsv")
    lines.append("  compat_policy_adjustments.tsv")
    lines.append("")
    lines.append("notes:")
    lines.append("  CJK rows are assigned first so CJK codepoints stay stable if optional non-CJK Big5 chars are later added.")
    lines.append("  Do not replace src/charmap.txt with charmap_big5_extension.txt; this is a fragment for future extension-aware import/build tools.")
    lines.append("  The DFS engine still needs a separate patch to enable pages and generate extension font bins.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")



def category_for_char(ch: str) -> str:
    if "\u4e00" <= ch <= "\u9fff" or "\u3400" <= ch <= "\u4dbf":
        return "cjk"
    if "\u3040" <= ch <= "\u309f" or "\u30a0" <= ch <= "\u30ff":
        return "kana"
    if "\u3100" <= ch <= "\u312f" or "\u31a0" <= ch <= "\u31bf":
        return "bopomofo"
    if "\uff00" <= ch <= "\uffef":
        return "fullwidth"
    cat = unicodedata.category(ch)
    if cat.startswith("P"):
        return "punctuation"
    if cat.startswith("S"):
        return "symbol"
    if cat.startswith("N"):
        return "number"
    return cat


def hex_unicode(ch: str) -> str:
    return "U+" + " ".join(f"{ord(c):04X}" for c in ch)


def big5_hex(ch: str) -> str:
    try:
        return ch.encode("big5").hex().upper()
    except UnicodeEncodeError:
        return ""


def parse_extra_chars_arg(repo: Path, args: argparse.Namespace) -> Set[str]:
    chars: Set[str] = set()
    if getattr(args, "extra_chars", ""):
        chars.update(args.extra_chars)
    f = getattr(args, "extra_chars_file", "")
    if f:
        path = repo_path(repo, f)
        if path.exists():
            chars.update(path.read_text(encoding="utf-8", errors="replace"))
        else:
            raise FileNotFoundError(path)
    # Remove ASCII whitespace/newlines from file input, but keep U+3000 as real glyph.
    chars.difference_update(set(" \t\r\n"))
    return chars

def main() -> int:
    ap = argparse.ArgumentParser(description="Build a physical DFS code table for Big5 extension-needed characters.")
    ap.add_argument("--version", action="store_true", help="Print version and exit")
    ap.add_argument("--repo", default=".", help="Repository root")
    ap.add_argument("--classification", default="reports/big5_extension/classification.tsv", help="Big5 classification.tsv from audit_big5_extension_feasibility.py")
    ap.add_argument("--dfs-pages", default="reports/dfs_pages/proposed_extension_pages.tsv", help="proposed_extension_pages.tsv from audit_dfs_physical_pages.py")
    ap.add_argument("--safe-lows", default="reports/dfs_pages/safe_low_template.tsv", help="safe_low_template.tsv from audit_dfs_physical_pages.py")
    ap.add_argument("--base-charmap", default="reports/charmap_chs_base.txt", help="Original/base CHS charmap")
    ap.add_argument("--current-charmap", default="src/charmap.txt", help="Current CHT charmap; used for audit/report only by default")
    ap.add_argument("--reserve-current-codes", choices=["yes", "no"], default="no", help="Also reserve codes currently present in --current-charmap. Normally keep this 'no' when rebuilding the canonical Big5 extension map from base sources, because src/charmap.txt may already contain stale/minimal/probe/full-extension entries.")
    ap.add_argument("--compat-policy", choices=["strict", "legacy"], default="strict", help="strict moves one-simplified-to-many-traditional variants such as 齣 away from the base glyph code and into extension; legacy keeps the old v1/v2 optimistic aliases.")
    ap.add_argument("--out-dir", default="reports/big5_extension_physical", help="Output directory")
    ap.add_argument("--target", choices=["cjk", "cjk-plus-extra", "all-visible"], default="cjk", help="Map only CJK extension chars, CJK plus explicit --extra-chars, or CJK plus selected visible Big5 non-CJK chars")
    ap.add_argument("--extra-chars", default="", help="Explicit extra non-CJK characters to assign extension slots, e.g. をんゥェ. Useful for text-required kana while keeping target=cjk-plus-extra compact.")
    ap.add_argument("--extra-chars-file", default="", help="Optional UTF-8 text file whose characters are added to --extra-chars.")
    ap.add_argument("--include-extra-categories", default="bopomofo,kana,fullwidth,punctuation,symbol,number", help="Extra non-CJK categories to include for --target all-visible")
    ap.add_argument("--use-tail-spares", choices=["auto", "yes", "no"], default="auto", help="Use safe unused holes on existing legacy tail pages when extension pages are not enough")
    ap.add_argument("--tail-spare-pages", default="$2E", help="Comma/range list of existing pages whose unused template lows may be used as overflow, e.g. $2E or $2D-$2E")
    ap.add_argument("--apply", action="store_true", help="Also copy stable maps into src/dfs/maps/")
    args = ap.parse_args()

    if args.version:
        print(VERSION)
        return 0

    repo = Path(args.repo).resolve()
    classification_path = repo_path(repo, args.classification)
    dfs_pages_path = repo_path(repo, args.dfs_pages)
    safe_lows_path = repo_path(repo, args.safe_lows)
    base_charmap_path = repo_path(repo, args.base_charmap)
    current_charmap_path = repo_path(repo, args.current_charmap)
    out_dir = repo_path(repo, args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    classes = read_tsv(classification_path)
    classes, compat_adjustments = apply_strict_compat_policy(classes, args.compat_policy)
    pages = parse_pages(dfs_pages_path)
    lows = parse_low_template(safe_lows_path)
    _, base_code_to_chars = parse_charmap(base_charmap_path)
    _, current_code_to_chars = parse_charmap(current_charmap_path)

    # IMPORTANT:
    # The canonical extension table must be rebuildable from stable sources.
    # Earlier CHT/minimal/probe/full-extension runs may already have written
    # temporary codes into src/charmap.txt. If we reserve all current codes here,
    # the allocator thinks the extension pages are already occupied and reports
    # only a handful of remaining slots. Therefore the default is to reserve only
    # the original/base CHS map. Use --reserve-current-codes yes only for a special
    # audit where the current charmap is intentionally authoritative.
    used_codes = set(base_code_to_chars)
    if args.reserve_current_codes == "yes":
        used_codes |= set(current_code_to_chars)

    cjk_rows = sorted(
        [r for r in classes if is_extension_needed(r) and r.get("category") == "cjk"],
        key=row_sort_key,
    )
    extra_categories = {x.strip() for x in args.include_extra_categories.split(",") if x.strip()}
    manual_extra_chars = parse_extra_chars_arg(repo, args)

    if args.target == "all-visible":
        extra_candidates = [
            r for r in classes
            if is_extension_needed(r) and r.get("category") in extra_categories and r.get("category") != "cjk"
        ]
    elif args.target == "cjk-plus-extra":
        extra_candidates = [
            r for r in classes
            if is_extension_needed(r) and r.get("ch", "") in manual_extra_chars and r.get("category") != "cjk"
        ]
    else:
        extra_candidates = []

    # Synthetic extra rows for characters not present in classification.tsv, useful
    # for project-local glyphs or non-Big5 symbols. They still get extension slots.
    known_chars = {r.get("ch", "") for r in classes}
    for ch in sorted(manual_extra_chars):
        if not ch or ch in known_chars:
            continue
        extra_candidates.append({
            "ch": ch,
            "unicode": hex_unicode(ch),
            "big5": big5_hex(ch),
            "category": category_for_char(ch),
            "t2s": "",
            "dfs_code": "",
            "class_name": "extension-needed-manual-extra",
            "extension_needed": "yes",
            "note": "manual --extra-chars synthetic row",
        })

    # Avoid duplicating any char already assigned in CJK rows.
    cjk_chars = {r.get("ch", "") for r in cjk_rows}
    dedup = {}
    for r in extra_candidates:
        ch = r.get("ch", "")
        if ch and ch not in cjk_chars:
            dedup[ch] = r
    extra_rows = sorted(dedup.values(), key=row_sort_key)

    extension_slots = build_extension_slots(pages, lows, used_codes)
    needed = len(cjk_rows) + (len(extra_rows) if args.target == "all-visible" else 0)

    tail_pages: List[int] = []
    tail_slots: List[Slot] = []
    if args.use_tail_spares == "yes" or (args.use_tail_spares == "auto" and needed > len(extension_slots)):
        tail_pages = parse_tail_spare_pages(args.tail_spare_pages)
        tail_slots = build_tail_spare_slots(tail_pages, lows, used_codes | {s.code for s in extension_slots}, base_code_to_chars, current_code_to_chars)

    slots = extension_slots + tail_slots
    ext_rows, charmap_rows = make_assignment_rows(cjk_rows, extra_rows, slots, args.target)
    compat_rows = make_compat_rows(classes)
    full_rows = make_full_rows(compat_rows, ext_rows)

    ext_fields = ["ext_index", "char", "unicode", "big5", "category", "t2s", "dfs_code", "page", "low", "slot_source", "compat_class", "note"]
    compat_fields = ["char", "unicode", "big5", "category", "dfs_code", "compat_class", "t2s", "base_char_at_code", "ime_reserved", "note"]
    full_fields = ["char", "unicode", "big5", "category", "dfs_code", "compat_class", "slot_source", "t2s", "note"]

    write_tsv(out_dir / "big5_extension_physical_map.tsv", ext_fields, ext_rows)
    write_tsv(out_dir / "big5_compat_base_map.tsv", compat_fields, compat_rows)
    write_tsv(out_dir / "big5_full_physical_map.tsv", full_fields, full_rows)
    write_charmap_txt(out_dir / "charmap_big5_extension.txt", charmap_rows)

    pages_used_rows = []
    by_page = defaultdict(lambda: Counter())
    for r in ext_rows:
        by_page[r["page"]][r["slot_source"]] += 1
    for p in sorted({s.page for s in slots}):
        page_s = fmt_page(p)
        pages_used_rows.append({
            "page": page_s,
            "assigned_extension_page": by_page[page_s].get("extension-page", 0),
            "assigned_tail_spare": by_page[page_s].get("legacy-tail-spare-hole", 0),
            "capacity_template_lows": len(lows),
        })
    write_tsv(out_dir / "extension_pages_used.tsv", ["page", "assigned_extension_page", "assigned_tail_spare", "capacity_template_lows"], pages_used_rows)
    write_tsv(out_dir / "compat_policy_adjustments.tsv", ["dfs_code", "char", "big5", "old_class", "new_class", "old_extension_needed", "new_extension_needed", "reason"], compat_adjustments)

    write_summary(
        out_dir / "summary.txt",
        args,
        pages,
        lows,
        tail_pages,
        ext_rows,
        compat_rows,
        len(cjk_rows),
        len(extra_rows),
        len(extension_slots),
        len(tail_slots),
    )

    if args.apply:
        maps_dir = repo / "src/dfs/maps"
        maps_dir.mkdir(parents=True, exist_ok=True)
        for name in [
            "big5_extension_physical_map.tsv",
            "big5_compat_base_map.tsv",
            "big5_full_physical_map.tsv",
            "charmap_big5_extension.txt",
            "extension_pages_used.tsv",
            "compat_policy_adjustments.tsv",
            "summary.txt",
        ]:
            src = out_dir / name
            dst = maps_dir / name
            dst.write_bytes(src.read_bytes())

    print((out_dir / "summary.txt").read_text(encoding="utf-8"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
